---
  -
    name: Me
    url: me.html
    newTab: false
  -
    name: Resume
    url: resume.html
    newTab: false
  -
    name: Me
    url: https://medium.com/@yrezgui
    newTab: true
  -
    name: Twitter
    url: https://twitter.com/yrezgui
    newTab: true
  -
    name: GitHub
    url: https://github.com/yrezgui
    newTab: true
