---
  -
    title: Front End Lead
    company: import.io
    url: https://import.io
    start: 2015-03-01
  -
    title: Web Developer
    company: import.io
    url: https://import.io
    start: 2014-10-01
    end: 2015-03-01
  -
    title: Web Developer
    company: GovernorHub
    url: https://governorhub.com
    start: 2013-07-01
    end: 2014-10-01
  -
    title: Web Developer
    company: Tequila Rapido
    url: http://www.tequilarapido.com
    start: 2012-09-01
    end: 2013-07-01
  -
    title: Web Developer
    company: Mediametrie eStat
    url: http://www.mediametrie-estat.com
    start: 2012-04-01
    end: 2012-07-01